"""
Device and Asset Management models.

Device      — a registered endpoint (laptop, desktop, server) running the agent
DeviceMetric — time-series hardware snapshots (CPU, RAM, Disk)
Asset       — any physical IT asset (monitor, keyboard, phone, chair)
AssetAssignment — audit trail of who had what asset when
"""

import uuid
import enum
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean, Date, DateTime, ForeignKey,
    Integer, Numeric, String, Text, JSON,
    Enum as SAEnum, Float,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import TenantModel


class DeviceOS(str, enum.Enum):
    WINDOWS = "windows"
    LINUX = "linux"
    MACOS = "macos"
    ANDROID = "android"
    IOS = "ios"
    OTHER = "other"


class DeviceStatus(str, enum.Enum):
    ONLINE = "online"
    OFFLINE = "offline"
    IDLE = "idle"
    LOCKED = "locked"
    SLEEPING = "sleeping"
    DECOMMISSIONED = "decommissioned"


class AssetStatus(str, enum.Enum):
    AVAILABLE = "available"
    ASSIGNED = "assigned"
    UNDER_REPAIR = "under_repair"
    DISPOSED = "disposed"
    LOST = "lost"


class Device(TenantModel):
    __tablename__ = "devices"

    # ── Identity ──────────────────────────────────────────────────
    hostname: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    device_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    serial_number: Mapped[str | None] = mapped_column(String(100), nullable=True, unique=True)
    asset_tag: Mapped[str | None] = mapped_column(String(50), nullable=True)

    # ── Agent ─────────────────────────────────────────────────────
    agent_id: Mapped[str] = mapped_column(
        String(64), nullable=False, unique=True, index=True,
        comment="UUID generated by the agent on first registration",
    )
    agent_version: Mapped[str | None] = mapped_column(String(20), nullable=True)
    agent_token_hash: Mapped[str] = mapped_column(
        String(255), nullable=False,
        comment="SHA-256 hash of the issued agent JWT",
    )

    # ── OS & Hardware ─────────────────────────────────────────────
    os_type: Mapped[DeviceOS] = mapped_column(
        SAEnum(DeviceOS, name="device_os_enum"), default=DeviceOS.WINDOWS
    )
    os_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    os_version: Mapped[str | None] = mapped_column(String(50), nullable=True)
    os_build: Mapped[str | None] = mapped_column(String(50), nullable=True)
    bios_version: Mapped[str | None] = mapped_column(String(100), nullable=True)
    motherboard: Mapped[str | None] = mapped_column(String(200), nullable=True)

    cpu_model: Mapped[str | None] = mapped_column(String(200), nullable=True)
    cpu_cores: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cpu_threads: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ram_total_gb: Mapped[float | None] = mapped_column(Float, nullable=True)
    disk_total_gb: Mapped[float | None] = mapped_column(Float, nullable=True)
    gpu_model: Mapped[str | None] = mapped_column(String(200), nullable=True)

    # ── Network ───────────────────────────────────────────────────
    public_ip: Mapped[str | None] = mapped_column(String(45), nullable=True)
    local_ip: Mapped[str | None] = mapped_column(String(45), nullable=True)
    mac_address: Mapped[str | None] = mapped_column(String(17), nullable=True)

    # ── Status ────────────────────────────────────────────────────
    status: Mapped[DeviceStatus] = mapped_column(
        SAEnum(DeviceStatus, name="device_status_enum"),
        default=DeviceStatus.OFFLINE,
        nullable=False,
        index=True,
    )
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_heartbeat_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Health score (0-100, computed by worker) ──────────────────
    health_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    health_issues: Mapped[list] = mapped_column(JSON, default=list, server_default="[]")

    # ── Assignment ────────────────────────────────────────────────
    assigned_employee_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("employees.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    branch_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("branches.id", ondelete="SET NULL"),
        nullable=True,
    )

    # ── Snapshot data (latest, updated by agent) ──────────────────
    installed_apps: Mapped[list] = mapped_column(JSON, default=list, server_default="[]")
    running_processes: Mapped[list] = mapped_column(JSON, default=list, server_default="[]")
    usb_devices: Mapped[list] = mapped_column(JSON, default=list, server_default="[]")
    printers: Mapped[list] = mapped_column(JSON, default=list, server_default="[]")
    monitors: Mapped[list] = mapped_column(JSON, default=list, server_default="[]")

    # ── Remote actions queue ──────────────────────────────────────
    pending_actions: Mapped[list] = mapped_column(JSON, default=list, server_default="[]")

    is_enrolled: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true")
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<Device {self.hostname!r} status={self.status}>"


class DeviceMetric(TenantModel):
    __tablename__ = "device_metrics"

    device_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )

    cpu_usage_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    ram_usage_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    ram_used_gb: Mapped[float | None] = mapped_column(Float, nullable=True)
    disk_usage_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    disk_used_gb: Mapped[float | None] = mapped_column(Float, nullable=True)
    gpu_usage_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    battery_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    battery_is_charging: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    network_bytes_sent: Mapped[int | None] = mapped_column(Integer, nullable=True)
    network_bytes_recv: Mapped[int | None] = mapped_column(Integer, nullable=True)
    uptime_seconds: Mapped[int | None] = mapped_column(Integer, nullable=True)
    active_user: Mapped[str | None] = mapped_column(String(100), nullable=True)


class DeviceScreenshot(TenantModel):
    """
    A single on-demand screen capture from a device.

    Deliberately on-demand only — the agent captures a screenshot when an
    admin explicitly requests one (queued via pending_actions, same
    mechanism as lock/restart), not on a continuous timer. Continuous
    screen recording is a much bigger privacy/consent/legal surface than
    this project needs to take on; point-in-time captures triggered by a
    specific admin action, with that admin's identity recorded, keeps
    this auditable and defensible as an IT-support tool rather than
    surveillance software.
    """
    __tablename__ = "device_screenshots"

    device_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    storage_key: Mapped[str] = mapped_column(String(500), nullable=False)
    mime_type: Mapped[str] = mapped_column(String(50), nullable=False, default="image/png")
    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    width: Mapped[int | None] = mapped_column(Integer, nullable=True)
    height: Mapped[int | None] = mapped_column(Integer, nullable=True)
    captured_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    requested_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Who asked for this capture — kept for audit purposes",
    )


class DeviceAlertType(str, enum.Enum):
    FLAGGED_APP_USAGE = "flagged_app_usage"       # active window/app title matched the watch-list
    FLAGGED_BROWSING = "flagged_browsing"         # a visited domain matched the watch-list


class DeviceAlert(TenantModel):
    """
    A flagged, non-work-activity event on a device — either an active
    window/application title or a browsed domain matching an
    organization-configured watch-list (see `activity_watchlist` in
    core/config.py).

    IMPORTANT — scope boundary, read before extending this model:
    This table intentionally does NOT store a full activity or browsing
    log. It stores only the events that matched a configured watch-list
    entry (e.g., "visited a known social-media domain during work
    hours"), never the employee's complete window-usage or browsing
    history. Capturing everything a device does — every URL visited,
    every window title, personal searches, banking, health, job-hunting
    activity, etc. — is a materially larger privacy intrusion than
    catching policy violations, carries far greater legal exposure
    (GDPR Art. 5 data-minimization, many US state monitoring-disclosure
    laws, employee-privacy statutes in several jurisdictions), and is not
    necessary to serve the stated business need. If a future requirement
    genuinely needs full activity logging, that decision should be made
    explicitly, with legal review, as a new and clearly-labeled
    capability — not accreted onto this table.

    Legal/compliance note (not legal advice — consult counsel per
    jurisdiction): device monitoring of this kind typically requires the
    organization to give employees clear advance notice of what is
    monitored and why (see the agent's first-run consent notice and the
    always-visible system tray indicator). Several jurisdictions require
    more than notice — e.g., a documented legitimate-interest basis under
    GDPR, or two-party consent for some forms of monitoring. Do not
    enable this feature for an organization without confirming their
    disclosure/consent obligations have been met.
    """
    __tablename__ = "device_alerts"

    device_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    alert_type: Mapped[DeviceAlertType] = mapped_column(
        SAEnum(DeviceAlertType, name="device_alert_type_enum"), nullable=False, index=True
    )
    matched_term: Mapped[str] = mapped_column(
        String(200), nullable=False, comment="The watch-list entry that matched (e.g. 'facebook.com')"
    )
    detail: Mapped[str] = mapped_column(
        String(500), nullable=False,
        comment="Window title for flagged_app_usage, or the matched domain for flagged_browsing — never a full URL with path/query, to avoid capturing search terms or personal content in links",
    )
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    is_acknowledged: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false", nullable=False)


class DeviceAllowedApp(TenantModel):
    """
    A per-device override that suppresses flagged-activity alerts for one
    specific app/domain, on one specific device.

    This sits ABOVE the global watch-list (settings.DEVICE_ACTIVITY_WATCHLIST):
    if "whatsapp.com" is in the org's global watch-list but this table has
    a row for (device_X, "whatsapp.com"), device_X never generates an
    alert for WhatsApp, while every other device still does. Use case:
    an employee who's approved to use WhatsApp for work communication
    shouldn't keep tripping the same alert every day.

    Checked at alert-*creation* time in the upload_alerts endpoint, not
    on the agent — the agent has no idea what's allowed or not, it just
    reports every watch-list match it sees. This means an admin can
    change an allow-list entry and it takes effect immediately on the
    next upload, without touching the agent or waiting for a redeploy.
    """
    __tablename__ = "device_allowed_apps"

    device_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    domain_or_app: Mapped[str] = mapped_column(
        String(200), nullable=False,
        comment="Normalized base label, e.g. 'whatsapp.com' — matched the same way the watch-list itself matches",
    )
    reason: Mapped[str | None] = mapped_column(String(300), nullable=True)
    allowed_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Which admin granted this exception — kept for audit purposes",
    )


class Asset(TenantModel):
    __tablename__ = "assets"

    name: Mapped[str] = mapped_column(String(200), nullable=False)
    asset_tag: Mapped[str] = mapped_column(String(50), nullable=False, unique=True, index=True)
    category: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    sub_category: Mapped[str | None] = mapped_column(String(100), nullable=True)
    brand: Mapped[str | None] = mapped_column(String(100), nullable=True)
    model: Mapped[str | None] = mapped_column(String(200), nullable=True)
    serial_number: Mapped[str | None] = mapped_column(String(100), nullable=True, unique=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    status: Mapped[AssetStatus] = mapped_column(
        SAEnum(AssetStatus, name="asset_status_enum"),
        default=AssetStatus.AVAILABLE,
        nullable=False,
        index=True,
    )

    purchase_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    purchase_cost: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    purchase_order_number: Mapped[str | None] = mapped_column(String(100), nullable=True)
    vendor: Mapped[str | None] = mapped_column(String(200), nullable=True)

    warranty_expiry: Mapped[date | None] = mapped_column(Date, nullable=True)
    warranty_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    location: Mapped[str | None] = mapped_column(String(200), nullable=True)
    branch_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("branches.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Currently assigned employee (denormalized for fast queries)
    assigned_employee_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("employees.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    assigned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    image_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    custom_fields: Mapped[dict] = mapped_column(JSON, default=dict, server_default="{}")

    assignments: Mapped[list["AssetAssignment"]] = relationship(
        "AssetAssignment", back_populates="asset"
    )

    def __repr__(self) -> str:
        return f"<Asset {self.asset_tag!r} {self.name!r}>"


class AssetAssignment(TenantModel):
    __tablename__ = "asset_assignments"

    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("assets.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    employee_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("employees.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    assigned_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    assigned_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    returned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    return_condition: Mapped[str | None] = mapped_column(String(50), nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    asset: Mapped["Asset"] = relationship("Asset", back_populates="assignments")

    def __repr__(self) -> str:
        return f"<AssetAssignment asset={self.asset_id} employee={self.employee_id}>"
